spring.application.name=sas-chat
spring.project.version=1.0.0

server.port=6010
server.servlet.contextPath=/sas

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/sas-chat-sphere?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=admin
